### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by jethror1**
Initial working version of bclconvert DNAnexus app

Mostly a rewrite of eggd_bcl2fastq but with bclconvert as an asset.
Asset set in `dxapp.json` will need changing to 001_Reference once built there before merging.

Example job: https://platform.dnanexus.com/projects/GJxgb004bGXjGVjg4fBky7K6/monitor/job/GJyPVjQ4bGXfBXz630bkv84j

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1)

### CODE REVIEW

**Review by sophie22 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1)* status: all files reviewed, 2 unresolved discussions (waiting on @chrispyatt and @jethror1)

___
*[`dxapp.json` line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHYqnTO70t4ckisy6Ij:-NHYqnTO70t4ckisy6Ik:b-s23vw6) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/c27550b75cd08a42cf9aed6b4ac510ea9902f0b8/dxapp.json#L6)):*
> ```JSON
>   "version": "1.0.0",
>   "summary": "Converts Illumina data from BCL to FASTQ using bclconvert",
>   "dxapi": "1.0.0",
> ```

is it required to add the GitHub release property?
___
*[`README.md` line 30 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHYrce0A1S1XdmuaCPz:-NHYrce0A1S1XdmuaCQ-:bq7ykfk) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/c27550b75cd08a42cf9aed6b4ac510ea9902f0b8/README.md#L30)):*
> ```Markdown
> ## Dependencies
> The app depends on the bcl-convert asset built to DNAnexus.
> ```

could add an example dx run command

**Comment by jethror1** [comment]
Added extra tag to the job of peak memory usage of bclconvert to monitor instance usage: 
image

https://platform.dnanexus.com/projects/GJxgb004bGXjGVjg4fBky7K6/monitor/job/GJyzjZQ4bGXf4b6J65Z4Q890

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @chrispyatt and @sophie22)

___
*[`dxapp.json` line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHYqnTO70t4ckisy6Ij:-NHZCw4z4gkJPWMntVef:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/c27550b75cd08a42cf9aed6b4ac510ea9902f0b8/dxapp.json#L6)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

is it required to add the GitHub release property?
</blockquote></details>

Done.
___
*[`README.md` line 30 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHYrce0A1S1XdmuaCPz:-NHZCwWQ2KwJ1YviRM6a:b-a8vodu) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/c27550b75cd08a42cf9aed6b4ac510ea9902f0b8/README.md#L30)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

could add an example dx run command
</blockquote></details>

not sure this is needed since its dx run like any other app, and is going to go away (mostly / hopefully) with automation running it, the asset is set in the dxapp.json so doesn't need to be specified on running

**Review by sophie22 — CHANGES_REQUESTED** [review]
noice

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-:-NHZFjkCEGznbKPYkZCn:b-7m36bf)* status: all files reviewed, 1 unresolved discussion (waiting on @chrispyatt and @jethror1)

___
*[`README.md` line 30 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHYrce0A1S1XdmuaCPz:-NHZG0LZ9lnWem4PjP_G:b-mtzqx) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/c27550b75cd08a42cf9aed6b4ac510ea9902f0b8/README.md#L30)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

not sure this is needed since its dx run like any other app, and is going to go away (mostly / hopefully) with automation running it, the asset is set in the dxapp.json so doesn't need to be specified on running
</blockquote></details>

fair enough

**Review by sophie22 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrispyatt)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1)* status: all files reviewed, 4 unresolved discussions (waiting on @chrispyatt and @jethror1)

___
*[`dxapp.json` line 21 at r3](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHd2SfECGsU9nopD9iJ:-NHd2SfECGsU9nopD9iK:bws419q) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/f1b35b2f561af0ec7f34ab3257e5aee533a5245a/dxapp.json#L21)):*
> ```JSON
>       "name": "run_archive",
>       "label": "Archive of top level run folder",
>       "help": "One archived file containing the top level output from the run. This archive should contain RunInfo.xml and be named the same as the original file.",
> ```

Behaviour if sentinal and archive passed in?



_Code quote:_
```JSON
"help": "
```
___
*[`dxapp.json` line 29 at r3](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHd1cay9VgIcaGosvl_:-NHd1cay9VgIcaGosvla:b-g45aqu) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/f1b35b2f561af0ec7f34ab3257e5aee533a5245a/dxapp.json#L29)):*
> ```JSON
>       "name": "sample_sheet",
>       "label": "Sample sheet",
>       "help": "The sample sheet file in CSV format.",
> ```

How does this behave when a samplesheet is also included in the archive/sentinel?



_Code quote:_
```JSON
The sample sheet file in CSV format.
```
___
*[`README.md` line 16 at r3](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHd24Qt2igPxQHiQW2-:-NHd24Qt2igPxQHiQW20:b-kpikat) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/f1b35b2f561af0ec7f34ab3257e5aee533a5245a/README.md#L16)):*
> ```Markdown
> ## What data are required for this app to run?
> This app requires
> * SampleSheet.csv (included in the run data, associated to the sentinel file or provided with `-isample_sheet`)
> ```

Behavior if present in archive array/sentinel and passed to `-isample_sheet`?



_Code quote:_
```Markdown
included in the run data, associated to the sentinel file or provided with `-isample_sheet`
```
___
*[`src/code.sh` line 58 at r3](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHd4bHE6WPzaeNaICXT:-NHd4bHE6WPzaeNaICXU:b-rfgil6) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/f1b35b2f561af0ec7f34ab3257e5aee533a5245a/src/code.sh#L58)):*
> ```Shell
>   else
>     dx-jobutil-report-error "No sentinel record or run data provided as input"
>   fi
> ```

Should this be treated as an error?



_Code quote:_
```Shell
  else
    dx-jobutil-report-error "No sentinel record or run data provided as input"
  fi
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1)* status: all files reviewed, 4 unresolved discussions (waiting on @chrispyatt and @mattgarner)

___
*[`dxapp.json` line 21 at r3](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHd2SfECGsU9nopD9iJ:-NHdIBBk99HaLv4eC4Dw:b3stk40) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/f1b35b2f561af0ec7f34ab3257e5aee533a5245a/dxapp.json#L21)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Behaviour if sentinal and archive passed in?
</blockquote></details>

archive data is checked first, but both shouldn't be provided 
___
*[`dxapp.json` line 29 at r3](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHd1cay9VgIcaGosvl_:-NHdI5j66vFnVO9cunVr:b-e8pjbv) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/f1b35b2f561af0ec7f34ab3257e5aee533a5245a/dxapp.json#L29)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

How does this behave when a samplesheet is also included in the archive/sentinel?
</blockquote></details>

have updated the help, if passed it will override any in the upload data
___
*[`README.md` line 16 at r3](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHd24Qt2igPxQHiQW2-:-NHdIQnQ5W2s4M3lUfOZ:bkg0c1l) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/f1b35b2f561af0ec7f34ab3257e5aee533a5245a/README.md#L16)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Behavior if present in archive array/sentinel and passed to `-isample_sheet`?
</blockquote></details>

as above, have updated here too
___
*[`src/code.sh` line 58 at r3](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHd4bHE6WPzaeNaICXT:-NHdJ0PO2jjthvfrAeAa:b-jero0n) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/f1b35b2f561af0ec7f34ab3257e5aee533a5245a/src/code.sh#L58)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should this be treated as an error?
</blockquote></details>

it does and I think it should since it has nothing to do, `dx-jobutil-report-error` exits with error code 1 so will fail the job: https://github.com/dnanexus/dx-toolkit/blob/master/src/python/scripts/dx-jobutil-report-error

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrispyatt)

___
*[`src/code.sh` line 58 at r3](https://reviewable.io/reviews/eastgenomics/eggd_bclconvert/1#-NHd4bHE6WPzaeNaICXT:-NHdrNFN6o9wfwRVxtTX:b-xjmu3i) ([raw file](https://github.com/eastgenomics/eggd_bclconvert/blob/f1b35b2f561af0ec7f34ab3257e5aee533a5245a/src/code.sh#L58)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

it does and I think it should since it has nothing to do, `dx-jobutil-report-error` exits with error code 1 so will fail the job: https://github.com/dnanexus/dx-toolkit/blob/master/src/python/scripts/dx-jobutil-report-error
</blockquote></details>

Yes it does, brain clearly not working.

**Pull request merged**
